apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-mono
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-mono
  template:
    metadata:
      labels:
        app: load-mono
    spec:
      serviceAccountName: appsimulator
      nodeSelector:
        eks.amazonaws.com/nodegroup: qualtrics-ng
      containers:
        - name: app
          image: public.ecr.aws/neuron/pytorch-inference-neuronx:2.6.0-neuronx-py310-sdk2.23.0-ubuntu22.04
          imagePullPolicy: Always
          command:
            - /bin/bash
            - "-exc"
            - |
              set -x
              apt-get update
              pip install quart

              find /adhoc-python-packages-deb -type f -name '*.deb' -exec sh -c '
                for pkg; do
                  cp "$pkg" / &&
                  apt install -y "/$(basename "$pkg")"
                done
              ' _ {} +
              find /adhoc-python-packages-deb -type f -name '*.whl' -exec sh -c '
                for pkg; do
                  cp "$pkg" / &&
                  pip install "/$(basename "$pkg")"
                done
              ' _ {} +
              cp /adhoc-python-packages-deb/measure_and_publish.py / 
              python /measure_and_publish.py
              while true; do sleep 3600; done
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: adhoc-python-packages-deb-pvc
              mountPath: /adhoc-python-packages-deb
          env:
            - name: SVC_PREFIX
              value: "mono"
            - name: CW_NAMESPACE
              value: "DI/mono"
            - name: PROMPT_COUNT
              value: "hello"
            - name: REGION
              value: "us-west-2"
            - name: PROMPT_WORD
              value: "hello"
            - name: PROMPT_COUNT
              value: "16304"
            - name: SLEEP_INTERVAL
              value: "10"
            - name: CONCURRENCY
              value: "6"
            - name: HUGGINGFACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secrets
                  key: HUGGINGFACE_TOKEN
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: adhoc-python-packages-deb-pvc
          persistentVolumeClaim:
            claimName: adhoc-python-packages-deb-pvc
